apiVersion: batch/v1
kind: CronJob
metadata:
  name: dnsstats-{{ .Values.cronjob.identifier }}
  namespace: {{ .Values.namespace | default "dnsstats" }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.allowConcurrent | ternary "Allow" "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit | default 4 }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit | default 4 }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit | default 0 }}
      template:
        metadata:
          labels:
            app: dnsstats-{{ .Values.cronjob.identifier }}
        spec:
          securityContext:
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
          restartPolicy: Never
          {{- with .Values.container.hostAliases }}
          hostAliases:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          initContainers:
          - name: k8s-secret-scribe
            securityContext:
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
              privileged: false
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 101
              runAsGroup: 101
              readOnlyRootFilesystem: true
            image: ncr.sky.nhn.no/dcn/k8s-secret-scribe:latest
            imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
            command:
              - /bin/sh
              - /scripts/k8s-secret-scribe.sh
            env:
            - name: SECRETS_ROOT
              value: /secrets
            - name: OUTPUT_DIR
              value: /config/secrets
            volumeMounts:
            - name: config
              mountPath: /config
            - name: splunk-secret
              mountPath: /secrets/splunk
              readOnly: true
          containers:
            - name: dnsstats-{{ .Values.cronjob.identifier }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              securityContext:
                runAsNonRoot: true
                runAsUser: 101
                runAsGroup: 101
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  memory: {{ .Values.container.limits.memory.min }}
                  cpu: {{ .Values.container.limits.cpu.min }}
                limits:
                  memory: {{ .Values.container.limits.memory.max }}
                  cpu: {{ .Values.container.limits.cpu.max }}
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: appconfig
                  mountPath: /app/config.json
                  subPath: config.json
                - name: splunk-config
                  mountPath: /app/splunk.json
                  subPath: /app/splunk.json
                {{- if .Values.container.caBundle }}
                - name: cabundle
                  mountPath: /etc/ssl/certs/nhn-certbundle.crt
                  subPath: nhn-certbundle.crt
                {{- end }}
          volumes:
            - name: config
              emptyDir: {}
            - name: appconfig
              configMap:
                name: dnsstats-{{ .Values.cronjob.identifier }}-app-config
            - name: splunk-config
              configMap:
                name: dnsstats-{{ .Values.cronjob.identifier }}-splunk-config
            - name: splunk-secret
              secret:
                secretName: dnsstats-{{ .Values.cronjob.identifier }}-splunk-secret
            {{- if .Values.container.caBundle }}
            - name: cabundle
              configMap:
                name: nhn-certbundle
            {{- end }}