{{- if ne (lower (toString .Values.splunk.token.vault.enable)) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: dnsstats-{{ .Values.cronjob.identifier }}-secrets
  namespace: {{ .Values.namespace | default "dnsstats" }}
type: Opaque
data:
  token: {{ .Values.splunk.token.static | b64enc | quote }}
{{- end }}