{{- if eq (lower (toString .Values.splunk.token.vault.enable)) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dnsstats-{{ .Values.cronjob.identifier }}-splunk-secret
  namespace: {{ .Values.namespace | default "dnsstats" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao				
    kind: ClusterSecretStore				
  target:
    name: dnsstats-{{ .Values.cronjob.identifier }}-splunk-secret				
  data:
    - secretKey: token
      remoteRef:
        key: /dnsstats
        property: splunk-token
{{- end }}