{{- if .Values.splunk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsstats-{{ .Values.cronjob.identifier }}-splunk-config
  namespace: {{ .Values.namespace | default "dnsstats" }}
stringData:
  splunk.json: |
    {
      "endpoint_url": {{ .Values.splunk.endpoint | quote }},
      "disable_tls": {{ .Values.splunk.disable_tls_warning }},
      "hec_index": {{ .Values.splunk.index | quote }},
      "hec_source": {{ .Values.splunk.source | quote }},
      "hec_sourcetype": {{ .Values.splunk.sourcetype | quote }}
    }
{{- end }}